// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUDCSNXVBFluivdnIX8cMy-FFmYlpU4A',
    appId: '1:1000838947869:web:f1839b0c2ad5a2736ad2f4',
    messagingSenderId: '1000838947869',
    projectId: 'photoblog-565fc',
    authDomain: 'photoblog-565fc.firebaseapp.com',
    databaseURL: 'https://photoblog-565fc.firebaseio.com',
    storageBucket: 'photoblog-565fc.firebasestorage.app',
    measurementId: 'G-DFH7HBSZET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4t0kecxDauNkby28lHMeDbfaymHEKp48',
    appId: '1:1000838947869:android:0aec7927dea4e67d6ad2f4',
    messagingSenderId: '1000838947869',
    projectId: 'photoblog-565fc',
    databaseURL: 'https://photoblog-565fc.firebaseio.com',
    storageBucket: 'photoblog-565fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDm6GZFHeblbbajOpSd9TXSCc0h4Z1GmQ',
    appId: '1:1000838947869:ios:9e36d8e06641bdf66ad2f4',
    messagingSenderId: '1000838947869',
    projectId: 'photoblog-565fc',
    databaseURL: 'https://photoblog-565fc.firebaseio.com',
    storageBucket: 'photoblog-565fc.firebasestorage.app',
    androidClientId: '1000838947869-6k92qt2vmisefbf8bc666fjj1s7dk32t.apps.googleusercontent.com',
    iosClientId: '1000838947869-9ebnci5bv6p5lvqm0ed9foagb3mlat57.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
